Repository AY2122S2-CS2103T-W09-3/tp, pull requests merged in 2022-03, with the labels that each got.

#19 Update README, AboutUs. Add Jin Lin's PPP.
  README.md
  docs/AboutUs.md
  docs/images/Ui.png
  docs/images/jltham.png
  docs/team/jltham.md
  docs/team/johndoe.md
Labels: type.Task, priority.High

#20 Update UG.
  docs/UserGuide.md
  docs/images/johndoe.png
Labels: type.Task, priority.High

#52 v1.1 pr
  docs/AboutUs.md
Labels: priority.High

#69 Branch v1.2
  data/expenseexpert.json
  docs/team/talkintomato.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/SetBudgetCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ExpenseExpertParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SetBudgetCommandParser.java
  src/main/java/seedu/address/model/ExpenseExpert.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyExpenseExpert.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/budget/Budget.java
  src/main/java/seedu/address/model/expense/Amount.java
  src/main/java/seedu/address/storage/JsonAdaptedBudget.java
  src/main/java/seedu/address/storage/JsonSerializableExpenseExpert.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/SetBudgetCommandTest.java
  src/test/java/seedu/address/model/ExpenseExpertTest.java
  src/test/java/seedu/address/model/budget/BudgetTest.java
  src/test/java/seedu/address/model/expense/AmountTest.java
  src/test/java/seedu/address/storage/JsonAdaptedBudgetTest.java
  src/test/java/seedu/address/testutil/BudgetBuilder.java
  src/test/java/seedu/address/testutil/TypicalExpenses.java
Labels: type.Task, priority.High

#79 Date Testing and Bugs Fixed
  data/expenseexpert.json
  docs/AboutUs.md
  docs/team/lamwj98.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/storage/JsonAdaptedExpense.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditExpenseDescriptorTest.java
  src/test/java/seedu/address/model/expense/ExpenseCategoryTest.java
  src/test/java/seedu/address/model/expense/ExpenseDateTest.java
  src/test/java/seedu/address/model/expense/ExpenseTest.java
  src/test/java/seedu/address/model/expense/UniqueExpenseListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedExpenseTest.java
  src/test/java/seedu/address/testutil/ExpenseBuilder.java
  src/test/java/seedu/address/testutil/ExpenseUtil.java
  src/test/java/seedu/address/testutil/TypicalExpenses.java
Labels: priority.High

#84 Update GUI for budget display.
  data/expenseexpert.json
  src/main/java/seedu/address/model/ExpenseExpert.java
  src/main/java/seedu/address/ui/BudgetDisplay.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/BudgetDisplay.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Task, priority.Medium

#88 Filter feature & ExpenseDate (String to LocalDate data)
  data/expenseexpert.json
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/lamwj98.md
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ExpenseExpertParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/expense/ExpenseDate.java
  src/main/java/seedu/address/model/expense/ExpenseDateIsParsedDatePredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedExpense.java
  src/main/java/seedu/address/ui/ExpenseCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/expense/DescriptionContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/expense/ExpenseDateIsParsedDatePredicateTest.java
  src/test/java/seedu/address/model/expense/ExpenseDateTest.java
  src/test/java/seedu/address/testutil/ExpenseUtil.java
  src/test/java/seedu/address/testutil/TypicalExpenses.java
Labels: type.Story, type.Enhancement, priority.Medium

#91 Create date attribute for Budget for functionalities related to time
  .gitignore
  data/expenseexpert.json
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/SetBudgetCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SetBudgetCommandParser.java
  src/main/java/seedu/address/model/ExpenseExpert.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyExpenseExpert.java
  src/main/java/seedu/address/model/budget/Budget.java
  src/main/java/seedu/address/model/expense/Amount.java
  src/main/java/seedu/address/model/expense/Budget.java
  src/main/java/seedu/address/model/expense/Date.java
  src/main/java/seedu/address/model/expense/Expense.java
  src/main/java/seedu/address/model/expense/ExpenseDateIsParsedDatePredicate.java
  src/main/java/seedu/address/model/expense/UniqueExpenseList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedBudget.java
  src/main/java/seedu/address/storage/JsonAdaptedExpense.java
  src/main/java/seedu/address/ui/BudgetDisplay.java
  src/main/java/seedu/address/ui/ExpenseCard.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/SetBudgetCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/budget/BudgetTest.java
  src/test/java/seedu/address/model/expense/AmountTest.java
  src/test/java/seedu/address/model/expense/BudgetTest.java
  src/test/java/seedu/address/model/expense/DateTest.java
  src/test/java/seedu/address/model/expense/ExpenseDateTest.java
  src/test/java/seedu/address/model/expense/ExpenseTest.java
  src/test/java/seedu/address/storage/JsonAdaptedBudgetTest.java
  src/test/java/seedu/address/storage/JsonAdaptedExpenseTest.java
  src/test/java/seedu/address/testutil/BudgetBuilder.java
  src/test/java/seedu/address/testutil/EditExpenseDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ExpenseBuilder.java
  src/test/java/seedu/address/testutil/ExpenseUtil.java
  src/test/java/seedu/address/testutil/TypicalBudgets.java
  src/test/java/seedu/address/testutil/TypicalExpenses.java
Labels: type.Task, priority.High

#111 Enhanced Filter Feature
  data/expenseexpert.json
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/lamwj98.md
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/expense/ExpenseCategoryIsParsedCategoryPredicate.java
  src/main/java/seedu/address/model/expense/PredicateChain.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/model/expense/ExpenseCategoryIsParsedCategoryPredicateTest.java
  src/test/java/seedu/address/model/expense/PredicateChainTest.java
  src/test/java/seedu/address/testutil/TypicalExpenses.java
Labels: type.Enhancement
